
import { Inter } from "next/font/google";
import React from "react";
import "./globals.css";
import Navbar from "../components/Navbar";
import { getServerSession } from "next-auth";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Doctor App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="flex flex-row overflow-auto h-screen bg-gray-100">
        {
        session? <Navbar className="w-full"/>: null
        }
        {children}
        
        </div>
      </body>
    </html>
  );
}
